version: "3.8"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WATERMARK_KEY=${WATERMARK_KEY}
      - WATERMARK_S3_BUCKET=${WATERMARK_S3_BUCKET}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=redis://redis:6379/0
      - RATE_LIMIT_PER_MIN=30
    depends_on:
      - redis
  web:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
